//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace campusmvpAppInfoSVC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int FeatureId { get; set; }
        public int CourseId { get; set; }
        public string FeatureText { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
